# Copyright (c) 2026 Mockarty. All rights reserved.
# Licensed under the Mockarty SDK License Agreement. See LICENSE file for details.

"""Pydantic models for Mockarty API objects."""

from mockarty.models.autonomous_missions import (
    AutonomousMission,
    AutonomousMissionBudget,
    AutonomousMissionBudgetHint,
    AutonomousMissionContextRef,
    AutonomousMissionFlow,
    AutonomousMissionListResponse,
    AutonomousMissionSubmitRequest,
    AutonomousMissionSubmitResponse,
    MissionEffectiveSetting,
    MissionEffectiveSettings,
    MissionCancelRequest,
    MissionControlReceipt,
    MissionControlResponse,
    MissionStartRequest,
    MissionStartResponse,
    UnifiedMission,
)

from mockarty.models.chaos import (
    AffectedResource,
    ChaosConnectionResult,
    ChaosEvent,
    ChaosExperiment,
    ChaosMetrics,
    ChaosOperatorStatus,
    ChaosPreset,
    ChaosProfile,
    ChaosReport,
    ChaosResults,
    ChaosSnapshot,
    FaultConfig,
    HealthCheckResult,
    InfraProfile,
    MetricsSnapshot,
    MinMaxAvg,
    PhaseMetrics,
    SafetyConfig,
    ScheduleConfig,
    SteadyState,
    SteadyStateCheck,
    TargetConfig,
    TimelineEvent,
)
from mockarty.models.common import (
    AbortCriterion,
    ErrorResponse,
    HealthResponse,
    MockLogs,
    Page,
    PerfConfig,
    PerfOptions,
    PerfStage,
    RequestLog,
)
from mockarty.models.condition import AssertAction, Condition
from mockarty.models.contexts import (
    GraphQLRequestContext,
    GrpcRequestContext,
    HttpRequestContext,
    KafkaRequestContext,
    MCPRequestContext,
    RabbitMQRequestContext,
    SmtpRequestContext,
    SoapRequestContext,
    SocketRequestContext,
    SSERequestContext,
)
from mockarty.models.contract import (
    CheckCompatibilityRequest,
    Contract,
    ContractConfig,
    ContractResult,
    ContractValidationRequest,
    ContractValidationResult,
    ContractViolation,
    DriftDetectionRequest,
    PactMessageContent,
    PactMessageInteraction,
    PactProviderState,
    PactVerifyRequest,
    ValidatePayloadRequest,
)
from mockarty.models.economics import (
    LLMBudget,
    LLMBudgetList,
    LLMPrice,
    LLMPriceList,
    LLMUsageCost,
    LLMUsageForecast,
    LLMUsageGroup,
    LLMUsageOutcomeCost,
    LLMUsageReconciliation,
    LLMUsageRefund,
    LLMUsageReport,
    LLMUsageTotals,
    ResourcePrice,
    ResourcePriceList,
    ResourceUsageTotal,
)
from mockarty.models.entity_search import (
    ENTITY_SEARCH_DEFAULT_LIMIT,
    ENTITY_SEARCH_MAX_LIMIT,
    ENTITY_TYPE_CHAOS_EXPERIMENT,
    ENTITY_TYPE_CONTRACT_PACT,
    ENTITY_TYPE_FUZZ_CONFIG,
    ENTITY_TYPE_MOCK,
    ENTITY_TYPE_PERF_CONFIG,
    ENTITY_TYPE_TEST_PLAN,
    EntitySearchResponse,
    EntitySearchResult,
)
from mockarty.models.experience import (
    EXPERIENCE_KIND_DEFECT_ROOT_CAUSE,
    EXPERIENCE_KIND_MISSION_LESSON,
    EXPERIENCE_KIND_PITFALL,
    EXPERIENCE_KIND_PRODUCT_FACT,
    ExperienceItem,
    ExperienceRecordResponse,
    ExperienceReviewDetail,
    ExperienceReviewItem,
    ExperienceReviewMutation,
    ExperienceReviewPage,
    ExperienceReviewRelation,
    ExperienceReviewResponse,
    ExperienceSearchResponse,
)
from mockarty.models.folders import MockFolder
from mockarty.models.fuzzing import (
    FuzzingConfig,
    FuzzingResult,
    FuzzingRun,
    QuarantineEntry,
)
from mockarty.models.generator import (
    GeneratorPreview,
    GeneratorRequest,
    GeneratorResponse,
)
from mockarty.models.imports import ImportResult
from mockarty.models.llm_security import (
    LLMSecurityDelegation,
    LLMSecurityEvent,
    LLMSecurityEventsResponse,
    LLMSecurityFinding,
    LLMSecurityPolicy,
    LLMSecurityPolicyDocument,
    LLMSecurityPolicyRequest,
    LLMSecurityPolicyResponse,
    LLMSecurityRestrictions,
    LLMSecuritySandboxRequest,
    LLMSecuritySandboxResponse,
    LLMSecuritySource,
)
from mockarty.models.mock import (
    Callback,
    ContentResponse,
    Extract,
    Mock,
    MockVersion,
    OneOf,
    Proxy,
    ResponseScript,
    SaveMockResponse,
)
from mockarty.models.recorder import RecorderEntry, RecorderSession
from mockarty.models.store import (
    DeleteFromStoreRequest,
    StoreData,
    StoreEntry,
)
from mockarty.models.testrun import TestRun
from mockarty.models.undefined import UndefinedRequest

__all__ = [  # noqa: RUF022 - grouped by model domain for discoverability
    # Chaos models
    "AffectedResource",
    "ChaosConnectionResult",
    "ChaosEvent",
    "ChaosExperiment",
    "ChaosMetrics",
    "ChaosOperatorStatus",
    "ChaosPreset",
    "ChaosProfile",
    "ChaosReport",
    "ChaosResults",
    "ChaosSnapshot",
    "FaultConfig",
    "HealthCheckResult",
    "InfraProfile",
    "MetricsSnapshot",
    "MinMaxAvg",
    "PhaseMetrics",
    "SafetyConfig",
    "ScheduleConfig",
    "SteadyState",
    "SteadyStateCheck",
    "TargetConfig",
    "TimelineEvent",
    # Condition models
    "AssertAction",
    "Condition",
    # Entity-search models
    "ENTITY_SEARCH_DEFAULT_LIMIT",
    "ENTITY_SEARCH_MAX_LIMIT",
    "ENTITY_TYPE_CHAOS_EXPERIMENT",
    "ENTITY_TYPE_CONTRACT_PACT",
    "ENTITY_TYPE_FUZZ_CONFIG",
    "ENTITY_TYPE_MOCK",
    "ENTITY_TYPE_PERF_CONFIG",
    "ENTITY_TYPE_TEST_PLAN",
    "EntitySearchResponse",
    "EntitySearchResult",
    "EXPERIENCE_KIND_DEFECT_ROOT_CAUSE",
    "EXPERIENCE_KIND_MISSION_LESSON",
    "EXPERIENCE_KIND_PITFALL",
    "EXPERIENCE_KIND_PRODUCT_FACT",
    "ExperienceItem",
    "AutonomousMission",
    "AutonomousMissionBudget",
    "AutonomousMissionBudgetHint",
    "AutonomousMissionContextRef",
    "AutonomousMissionFlow",
    "AutonomousMissionListResponse",
    "AutonomousMissionSubmitRequest",
    "AutonomousMissionSubmitResponse",
    "MissionEffectiveSetting",
    "MissionEffectiveSettings",
    "MissionCancelRequest",
    "MissionControlReceipt",
    "MissionControlResponse",
    "MissionStartRequest",
    "MissionStartResponse",
    "UnifiedMission",
    "ExperienceRecordResponse",
    "ExperienceReviewDetail",
    "ExperienceReviewItem",
    "ExperienceReviewMutation",
    "ExperienceReviewPage",
    "ExperienceReviewRelation",
    "ExperienceReviewResponse",
    "ExperienceSearchResponse",
    "LLMPrice",
    "LLMPriceList",
    "LLMBudget",
    "LLMBudgetList",
    "LLMUsageCost",
    "LLMUsageGroup",
    "LLMUsageForecast",
    "LLMUsageOutcomeCost",
    "LLMUsageReconciliation",
    "LLMUsageReport",
    "LLMUsageRefund",
    "LLMUsageTotals",
    "ResourcePrice",
    "ResourcePriceList",
    "ResourceUsageTotal",
    # Common models
    "AbortCriterion",
    "ErrorResponse",
    "HealthResponse",
    "MockLogs",
    "Page",
    "PerfConfig",
    "PerfOptions",
    "PerfStage",
    "RequestLog",
    # Contract models
    "CheckCompatibilityRequest",
    "Contract",
    "ContractConfig",
    "ContractResult",
    "ContractValidationRequest",
    "ContractValidationResult",
    "ContractViolation",
    "DriftDetectionRequest",
    "PactMessageContent",
    "PactMessageInteraction",
    "PactProviderState",
    "PactVerifyRequest",
    "ValidatePayloadRequest",
    # Context models
    "GraphQLRequestContext",
    "GrpcRequestContext",
    "HttpRequestContext",
    "KafkaRequestContext",
    "MCPRequestContext",
    "RabbitMQRequestContext",
    "SmtpRequestContext",
    "SoapRequestContext",
    "SocketRequestContext",
    "SSERequestContext",
    # Folder models
    "MockFolder",
    # Fuzzing models
    "FuzzingConfig",
    "FuzzingResult",
    "FuzzingRun",
    "QuarantineEntry",
    # Generator models
    "GeneratorPreview",
    "GeneratorRequest",
    "GeneratorResponse",
    # Import models
    "ImportResult",
    # LLM security models
    "LLMSecurityDelegation",
    "LLMSecurityEvent",
    "LLMSecurityEventsResponse",
    "LLMSecurityFinding",
    "LLMSecurityPolicy",
    "LLMSecurityPolicyDocument",
    "LLMSecurityPolicyRequest",
    "LLMSecurityPolicyResponse",
    "LLMSecurityRestrictions",
    "LLMSecuritySandboxRequest",
    "LLMSecuritySandboxResponse",
    "LLMSecuritySource",
    # Mock models
    "Callback",
    "ContentResponse",
    "ResponseScript",
    "Extract",
    "Mock",
    "MockVersion",
    "OneOf",
    "Proxy",
    "SaveMockResponse",
    # Recorder models
    "RecorderEntry",
    "RecorderSession",
    # Store models
    "DeleteFromStoreRequest",
    "StoreData",
    "StoreEntry",
    # Test run models
    "TestRun",
    # Undefined request models
    "UndefinedRequest",
]
