# Copyright (c) 2026 Mockarty. All rights reserved.

"""Optional pytest helpers for the Pact DSL.

The main ``mockarty`` pytest plugin (``mockarty.testing.plugin``) is
auto-loaded via the ``pytest11`` entry point in ``pyproject.toml``.
This sub-module provides Pact-specific fixtures that users can
``import``/use without registering a second entry point.

Two fixtures are offered:

* ``pact_output_dir`` — function-scoped ``tmp_path``-backed directory
  for the pact.json files generated by the test. Override at the
  session level if you want all tests in one folder.
* ``pact_consumer_factory`` — function-scoped callable that returns a
  fresh :class:`Consumer` already pointing at ``pact_output_dir``.

Users who want fully manual control just don't import these — the
plugin is opt-in.
"""

from __future__ import annotations

from pathlib import Path
from typing import Callable

import pytest

from mockarty.pact.consumer import Consumer


@pytest.fixture
def pact_output_dir(tmp_path: Path) -> Path:
    """Function-scoped directory for pact.json files (uses ``tmp_path``)."""

    out = tmp_path / "pacts"
    out.mkdir(exist_ok=True)
    return out


@pytest.fixture
def pact_consumer_factory(pact_output_dir: Path) -> Callable[..., Consumer]:
    """Return a callable that builds a :class:`Consumer` for the current test.

    The factory pre-fills the output directory so each test's pact.json
    lands in its own tmp folder by default.
    """

    def _make(
        consumer: str,
        provider: str,
        spec_version: str = "V4",
    ) -> Consumer:
        return (
            Consumer(consumer)
            .with_provider(provider)
            .with_spec_version(spec_version)
            .with_output_dir(pact_output_dir)
        )

    return _make
